version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    ports:
      - 8090:80
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    restart: always
    ports: 
      - "1001:3306"
    environment:
      MYSQL_DATABASE: 'laraapp_db'
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: secret